install.packages("devtools")
install.packages("BiocManager")
BiocManager::install(pkgs = "GO.db")
devtools::install_github("ZJUDBlab/InterCellDB")
library(InterCellDB)  # 0.9.2
library(Seurat)       # 3.2.0
library(dplyr)        # 1.0.5
library(future)       # 1.21.0
library(future.apply)


seurat_obj <-readRDS("AUCell_tutorial/all_seurat_obj.rds")
head(seurat_obj)
celltype_info <- read.xlsx("D:/File/document/单细胞测序代码/cell_annot (6-Macro).xlsx")
head(celltype_info)
seurat_obj$celltype <- celltype_info$cells[match(seurat_obj$seurat_clusters, celltype_info$cluster)]
unique(seurat_obj$celltype)
unique(seurat_obj$orig.ident)
table(is.na(seurat_obj$orig.ident))  # 看看多少 NA
dim(seurat_obj)
unique(seurat_obj$celltype)
unique(seurat_obj$orig.ident)
seurat_obj <- subset(seurat_obj, subset = celltype %in% c("Endothelial cells", "Macrophages", "Granulocytes"))
seurat_obj <- subset(seurat_obj, subset = orig.ident %in% c("A2_EV"))
tmp.counts <- GetAssayData(seurat_obj, slot = "data")
colnames(tmp.counts) <- as.character(seurat_obj$celltype)
dim(tmp.counts)

tmp.counts[1:5, 1:5]
# 设置分组依据为细胞的 cluster
Idents(seurat_obj) <- "celltype"  # 或你自己的cluster列名
# 查找每个 cluster 相对于其他 cluster 的差异表达基因
deg_all <- FindAllMarkers(
  object = seurat_obj,
  only.pos = TRUE,         # 只保留上调基因
  min.pct = 0.1,          # 至少在25%的细胞中表达
  logfc.threshold = 0.1  # Log2 fold change 阈值
)
top10 <- deg_all %>% 
  group_by(cluster) %>% 
  top_n(n = 10, wt = avg_log2FC)

head(top10)
write.csv(deg_all, "E&M&G_clusters.csv", row.names = FALSE)
top_genes <- top10$gene
DoHeatmap(seurat_obj, features = top_genes) + NoLegend()
markers.used <-deg_all
colnames(markers.used) <- c("p_val", "LogFC", "pct.1", "pct.2", "PVal", "cluster", "gene")
head(markers.used)
unique(markers.used$cluster)

inter.obj <- CreateInterCellObject(markers.used, species = "mouse", add.exprs = TRUE, exprs.data = tmp.counts)
inter.obj <- SelectDBSubset(inter.obj,
        use.exp = TRUE,   # to use experimentally validated interactions
        exp.score.range = c(1, 1000),  # use all credibility score for 'use.exp'
        use.know = TRUE,  # to use pathway curated interactions
        know.score.range = c(1, 1000),  # use all credibility score for 'use.know'
        use.pred = TRUE,  # to use predicted interactions
        pred.score.range = c(1, 1000),  # use all credibility score for 'use.pred' 
        sel.action.mode = "binding",  # select physically associated ones
        sel.action.effect = "ALL")    # not limiting action effects

ListAllGeneType(inter.obj)
# fetch genes of interest. GO.db version is v3.8.2 here, different version may have non-identical result.
genes.receiver <- FetchGeneOI(inter.obj, 
        sel.location = "Plasma Membrane",  # fetch proteins located in plasma membrane
        sel.location.score = c(4,5),       # 4 and 5 are of high confidence
        sel.type = "Receptor",             # fetch those receptors
        #sel.go.terms = "GO:0006955"        # fetch [GO:0006955]immune response related proteins
        )

genes.sender <- FetchGeneOI(inter.obj, 
        sel.location = "Extracellular Region",  # fetch proteins located in extracellular region
        sel.location.score = c(4,5),    # 4 and 5 are of high confidence    
        #sel.go.terms = "GO:0006955"             # fetch [GO:0006955]immune response related proteins
        )
genes.receiver$property$location.score <- 5
genes.sender$property$location.score <- 5
#第 3 步：执行完整的网络分析
#在标准化计数矩阵上用 2 个并行过程进行 100 次细胞标记排列。在每次排列期间，重新计算每个基因和每个细胞簇的平均基因表达。
plan("multiprocess", workers = 2)  # package future provides the parallel interface, here create 2 parallel processes  
# using options(future.globals.maxSize=1024^2 * 1000) to get more space to run parallel process
tmp.permlist <- Tool.GenPermutation(inter.obj, tmp.counts, perm.times = 100)
plan("sequential")  # close the parallel processes
#然后，我们使用先前定制的基因和与 4 个平行过程的相互作用进行完整的网络分析。使用 p 值 0.05 <执行单尾统计检验。
plan("multiprocess", workers = 2)
inter.obj <- AnalyzeInterInFullView(inter.obj, 
		sel.some.genes.X = genes.receiver$genes,  # set the genes for receiver cells
		sel.some.genes.Y = genes.sender,    # set the genes for sender cells
		sel.exprs.change = "Xup.Yup",       # select genes up-regulated for both sender cells and receiver cells
		run.permutation = TRUE,             # run statistical test with permutation list
		perm.expression = tmp.permlist,     # given the permutation list, generated by `Tool.GenPermutation`
		perm.pval.sides = "one-side-large", # use one-tailed test
		perm.pval.cutoff = 0.05)            # p-value cutoff 0.05
plan("sequential")
#可以通过可视化或表输出进一步收集完整网络分析的结果。用户可以定义他们感兴趣的集群。
#在这里，我们从示例数据中选择肿瘤簇之间的相互作用，其中排除了涉及“LN T 细胞”、“内淋巴”、
#“内膜 LN”和“成纤维细胞 LN”簇的相互作用。
all.clusters <- ListAllClusters(inter.obj) 
#select.clusters <- c("Gpnmb Macro", "Lgals Macro", "Spp1 Macro", "Cxcl9 Macro","Cd206 Macro")               # list all clusters
#unused.clusters <- setdiff(all.clusters, select.clusters)  # select those clusters in tumor
used.clusters <- all.clusters
# 选择 all.clusters 中存在于 torm.LN.clusters 中的簇
used.clusters <- used.clusters[order(used.clusters)]
# show the result of full network analysis
fullview.result <- GetResultFullView(inter.obj, 
		show.clusters.in.x = used.clusters,
		show.clusters.in.y = used.clusters,
		plot.axis.x.name = "signal receiving cells",
		plot.axis.y.name = "signal sending cells",
		nodes.size.range = c(1,8))
pdf("all_plot.pdf", width=8, height=6)
Tool.ShowGraph(fullview.result)  # visualization
dev.off()
Tool.WriteTables(fullview.result, dir.path = "./")  # write result into csv file

#  第 4 步：进行细胞间分析
inter.obj <- FetchInterOI(inter.obj, cluster.x = "Granulocytes", cluster.y = "Macrophages" )
#4.1 总结动作模式和动作效果
inter.obj <- AnalyzeInterInAction(inter.obj)
#显示所有基因对的动作模式组成
used.action.mode <- c("activation", "inhibition", "catalysis", "reaction", "expression", "ptmod")  # action mode: not showing mode 'binding' and 'other'
used.color.mode <- c("#FB8072", "#80B1D3", "#8DD3C7", "#FFFFB3", "#BEBADA", "#FDB462")  # customized color, one-to-one corresponding to those in `used.action.mode`
action.mode.result <- GetResultPieActionMode(inter.obj, 
		limits.exprs.change = c("Xup.Yup"),
		limits.action.mode = used.action.mode,
		color.action.mode = used.color.mode)
Tool.ShowGraph(action.mode.result)
Tool.WriteTables(action.mode.result, dir.path = ".") 
#显示动作效果的组成。
action.effect.result <- GetResultPieActionEffect(inter.obj, limits.exprs.change = c("Xup.Yup"))
Tool.ShowGraph(action.effect.result)
#4.2 亚群和秩基因对
#过滤激活的基因对,即选择那些具有 “激活 ”作用模式或 “积极 ”作用效应的基因对。
inter.obj <- SelectInterSubset(inter.obj, 
		sel.action.mode = "activation",
		sel.action.effect = "positive",
		sel.action.merge.option = "union"
		)
result.inter.pairs <- GetResultTgCrosstalk(inter.obj, 
		func.to.use = list(
			Power = function(x) { log1p(x) },        # further log-transform the power
			Confidence = function(x) { 1/(1+x) }     # invert the confidence to show
		),  
		axis.order.xy = c("Power", "Power"),       # order genes by power
		axis.order.xy.decreasing = c(TRUE, TRUE),  # select if ordering is decreasing
		nodes.size.range = c(1, 10))
pdf("all_result.inter-G-M.pairs.pdf", width=8, height=6)
Tool.ShowGraph(result.inter.pairs)
dev.off()

#我们根据基因对的功效对它们进行排名，并选择那些排名靠前的基因。
inter.obj <- SelectInterSubset(inter.obj, 
		sel.some.genes.X = c("Cx3cr1","Ccrl2"),
		sel.some.genes.Y = c("Cxcl12","Hmgb1")
		)
#评估基因对的特异性
ListClusterGroups(inter.obj)
tmp.target.cluster.groups <- ListClusterGroups(inter.obj, 
		use.former = TRUE,
		cluster.former = c("Macrophages")  # list all crosstalk with Myeloid as receiver cell, this order is aligned with the X and Y axis in fullview result. In this example, clusters listed in X axis are the receiver cells.
		)
tmp.target.cluster.groups <- setdiff(tmp.target.cluster.groups, c("Macrophages~Macrophages", "Macrophages~Granulocytes"))
inter.obj <- AnalyzeInterSpecificity(inter.obj, 
		to.cmp.cluster.groups = tmp.target.cluster.groups
		)

result.specificity <- GetResultTgSpecificity(inter.obj,
		sel.uq.cnt.options = seq_along(tmp.target.cluster.groups),
		plot.uq.cnt.merged = TRUE, 
		plot.name.X.to.Y = FALSE,
		func.to.use = list(Power = function(x) { log1p(x) },
                       Confidence = function(x) { 1/(1+x) }),
		dot.size.range = c(2,8),
		dot.colour.seq = c("#00809D", "#EEEEEE", "#C30000"),
		dot.colour.value.seq = c(0, 0.4, 1)
		)
pdf("result.specificity.pdf", width=8, height=6)
Tool.ShowGraph(result.specificity)
dev.off()
#4.4 在空间模式中总结基因对
tmp.hide.locations <- setdiff(ListAllGeneLocation(inter.obj), c("Plasma Membrane","Extracellular Region"))  # select the subcellular locations allowed to show
set.seed(101L)  # set seed to make reproducible result, or gene will be re-arranged every time re-running GetResultTgCellPlot
result.sptialpattern <- GetResultTgCellPlot(inter.obj, 
		area.extend.times = 20,  # control the size of plotting. Increase the value by 10 when warnings ask to
		hide.other.area = TRUE,
		hide.locations.X = tmp.hide.locations,
		hide.locations.Y = tmp.hide.locations,
    expand.gap.radius.list = list(ECM = 8, CTP = 2, NC = 2, OTHER = 2),
		link.size = 0.3,
		link.alpha = 0.8,
		legend.manual.left.spacing = grid::unit(0.1, "cm")
		)
Tool.ShowGraph(result.sptialpattern)
result.inter.pairs$table$from.gene
result.inter.pairs$table$to.gene
result.inter.pairs$table$from.gene %in% genes.receiver$genes
result.inter.pairs$table$to.gene %in% genes.sender$genes
"Extracellular Region"